//get colums
export const GET_COLUMS_DANH_SACH_SAN_PHAM = "GET_COLUMS_DANH_SACH_SAN_PHAM";
export const GET_COLUMS_DANH_MUC_SAN_PHAM = "GET_COLUMS_DANH_MUC_SAN_PHAM";
export const GET_COLUMS_LOAI_SAN_PHAM = "GET_COLUMS_LOAI_SAN_PHAM";
export const GET_COLUMS_QUOC_GIA = "GET_COLUMS_QUOC_GIA";
export const GET_COLUMS_LOAI_NHO = "GET_COLUMS_LOAI_NHO";
export const GET_COLUMS_THUC_AN_KEM = "GET_COLUMS_THUC_AN_KEM";
export const GET_COLUMS_VUNG = "GET_COLUMS_VUNG";
export const GET_COLUMS_NHA_MAY = "GET_COLUMS_NHA_MAY";
export const GET_COLUMS_PHONG_CACH_LAM = "GET_COLUMS_PHONG_CACH_LAM";
export const GET_COLUMS_DANH_GIA_SP = "GET_COLUMS_DANH_GIA_SP";
export const GET_COLUMS_DANH_GIA_THUC_AN = "GET_COLUMS_DANH_GIA_SP_THUC_AN";
export const GET_COLUMS_DANH_SACH_KH = "GET_COLUMS_DANH_SACH_KH";
export const GET_COLUMS_DIA_CHI_GIAO_HANG = "GET_COLUMS_DIA_CHI_GIAO_HANG";
export const GET_COLUMS_TINH_THANH_PHO = "GET_COLUMS_TINH_THANH_PHO";
export const GET_COLUMS_QUAN_HUYEN = "GET_COLUMS_QUAN_HUYEN";
export const GET_COLUMS_DANH_SACH_DON_HANG = "GET_COLUMS_DANH_SACH_DON_HANG";

//get data
export const GET_DANH_SACH_SAN_PHAM = "GET_DANH_SACH_SAN_PHAM";
export const GET_DANH_MUC_SAN_PHAM = "GET_DANH_MUC_SAN_PHAM";
export const GET_LOAI_SAN_PHAM = "GET_LOAI_SAN_PHAM";
export const GET_QUOC_GIA = "GET_QUOC_GIA";
export const GET_LOAI_NHO = "GET_LOAI_NHO";
export const GET_THUC_AN_KEM = "GET_THUC_AN_KEM";
export const GET_VUNG = "GET_VUNG";
export const GET_NHA_MAY = "GET_NHA_MAY";
export const GET_PHONG_CACH_LAM = "GET_PHONG_CACH_LAM";
export const GET_DANH_GIA_SP = "GET_DANH_GIA_SP";
export const GET_DANH_GIA_THUC_AN = "GET_DANH_GIA_THUC_AN";
export const GET_DANH_SACH_KHACH_HANG = "GET_DANH_SACH_KHACH_HANG";
export const GET_DIA_CHI_GIAO_HANG = "GET_DIA_CHI_GIAO_HANG";
export const GET_TINH_THANH_PHO = "GET_TINH_THANH_PHO";
export const GET_QUAN_HUYEN = "GET_QUAN_HUYEN";
export const GET_DANH_SACH_DON_HANG = "GET_DANH_SACH_DON_HANG";
//sidebar
export const GETDATAMENU = "DATAMENU";
export const GETRESULTTOGGLE = "GETRESULTTOGGLE";
// <<<<<<< HEAD

//search
export const SEARCH_NAME = "SEARCH_NAME";
export const SEARCH_ID = "SEARCH_ID";
// =======

//select
export const GET_LOAI_DANH_SACH_SAN_PHAM = "GET_LOAI_DANH_SACH_SAN_PHAM";
export const GET_TRANG_THAI_DANH_SACH_SAN_PHAM =
  "GET_TRANG_THAI_DANH_SACH_SAN_PHAM";

export const GETWIDTHTOSIDEBAR = "GETWIDTHTOSIDEBAR";
// <<<<<<< HEAD
// // >>>>>>> 48f0b2ff7800a7531f65845c4cbfa09ac9721872
// =======

// Login
export const CKECKLOGIN = "CKECKLOGIN";
export const LOGOUT = "LOGOUT";

// >>>>>>> origin/login
